site_name: Hydra API documentation

theme:
  name: "mkdocs"

plugins:
- search

- mkdocstrings:
      default_handler: python
      handlers:
        python:
          load_external_modules: true
          paths: [../../../Hydra]
