title: Hydra Gibbs sampler
description: A Bayesian sampling framework for data from 21cm arrays

remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
